#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHInfosyp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBInfosyp")]
	public partial class ConexDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertBancos(Bancos instance);
    partial void UpdateBancos(Bancos instance);
    partial void DeleteBancos(Bancos instance);
    partial void InsertEmpleados(Empleados instance);
    partial void UpdateEmpleados(Empleados instance);
    partial void DeleteEmpleados(Empleados instance);
    partial void InsertEmpresas(Empresas instance);
    partial void UpdateEmpresas(Empresas instance);
    partial void DeleteEmpresas(Empresas instance);
    partial void InsertRegalias(Regalias instance);
    partial void UpdateRegalias(Regalias instance);
    partial void DeleteRegalias(Regalias instance);
    partial void InsertSeguros(Seguros instance);
    partial void UpdateSeguros(Seguros instance);
    partial void DeleteSeguros(Seguros instance);
    partial void InsertPagos(Pagos instance);
    partial void UpdatePagos(Pagos instance);
    partial void DeletePagos(Pagos instance);
    #endregion
		
		public ConexDBDataContext() : 
				base(global::RHInfosyp.Properties.Settings.Default.DBInfosypConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bancos> Bancos
		{
			get
			{
				return this.GetTable<Bancos>();
			}
		}
		
		public System.Data.Linq.Table<Empleados> Empleados
		{
			get
			{
				return this.GetTable<Empleados>();
			}
		}
		
		public System.Data.Linq.Table<Empresas> Empresas
		{
			get
			{
				return this.GetTable<Empresas>();
			}
		}
		
		public System.Data.Linq.Table<Regalias> Regalias
		{
			get
			{
				return this.GetTable<Regalias>();
			}
		}
		
		public System.Data.Linq.Table<Seguros> Seguros
		{
			get
			{
				return this.GetTable<Seguros>();
			}
		}
		
		public System.Data.Linq.Table<Pagos> Pagos
		{
			get
			{
				return this.GetTable<Pagos>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AgregarBancos")]
		public int Sp_AgregarBancos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, estatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_BorrarBancos")]
		public int Sp_BorrarBancos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_EditarBancos")]
		public int Sp_EditarBancos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, estatus, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_ConsultaBancos")]
		public ISingleResult<Sp_ConsultaBancosResult> Sp_ConsultaBancos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Sp_ConsultaBancosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_BuscarBancos")]
		public ISingleResult<Sp_BuscarBancosResult> Sp_BuscarBancos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<Sp_BuscarBancosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AgregarEmpresas")]
		public int Sp_AgregarEmpresas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_BorrarEmpresas")]
		public int Sp_BorrarEmpresas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_BuscarEmpresas")]
		public ISingleResult<Sp_BuscarEmpresasResult> Sp_BuscarEmpresas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<Sp_BuscarEmpresasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_EditarEmpresas")]
		public int Sp_EditarEmpresas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_ConsultarEmpresas")]
		public ISingleResult<Sp_ConsultarEmpresasResult> Sp_ConsultarEmpresas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Sp_ConsultarEmpresasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AgregarSeguros")]
		public int Sp_AgregarSeguros([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_BorrarSeguros")]
		public int Sp_BorrarSeguros([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_BuscarSeguros")]
		public ISingleResult<Sp_BuscarSegurosResult> Sp_BuscarSeguros([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<Sp_BuscarSegurosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_EditarSeguros")]
		public int Sp_EditarSeguros([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_ConsultarSeguros")]
		public ISingleResult<Sp_ConsultarSegurosResult> Sp_ConsultarSeguros()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Sp_ConsultarSegurosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AgregarEmpleado")]
		public int Sp_AgregarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> sueldo_fijo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nocuenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string puesto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresaid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> seguroid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> bancoid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombres, apellidos, edad, sueldo_fijo, cedula, nocuenta, puesto, empresaid, seguroid, bancoid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_BuscarEmpleados")]
		public ISingleResult<Sp_BuscarEmpleadosResult> Sp_BuscarEmpleados([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cedula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, cedula);
			return ((ISingleResult<Sp_BuscarEmpleadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_BorrarEmpleado")]
		public int Sp_BorrarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cedula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombres, cedula);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_ConsultaEmpleados")]
		public ISingleResult<Sp_ConsultaEmpleadosResult> Sp_ConsultaEmpleados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Sp_ConsultaEmpleadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_EditarEmpleado")]
		public int Sp_EditarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> sueldo_fijo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nocuenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string puesto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresaid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> seguroid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> bancoid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombres, apellidos, edad, sueldo_fijo, cedula, nocuenta, puesto, empresaid, seguroid, bancoid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ConsultaPagoRegistrado")]
		public ISingleResult<ConsultaPagoRegistradoResult> ConsultaPagoRegistrado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idempleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idempleado);
			return ((ISingleResult<ConsultaPagoRegistradoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarPagos")]
		public int SP_AgregarPagos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> impuesto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> totalcobrado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> reembolsogastos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> horasextras, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> bonoespecial, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> segurosalud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> adicional, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empleadoid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> sueldobruto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), impuesto, totalcobrado, reembolsogastos, horasextras, bonoespecial, segurosalud, adicional, empleadoid, sueldobruto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AgregarRegalia")]
		public int Sp_AgregarRegalia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> monto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empleadoid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), monto, empleadoid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_ConsultaRegalia")]
		public ISingleResult<Sp_ConsultaRegaliaResult> Sp_ConsultaRegalia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idempleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idempleado, nombre);
			return ((ISingleResult<Sp_ConsultaRegaliaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ConsultaPago")]
		public ISingleResult<SP_ConsultaPagoResult> SP_ConsultaPago([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idempleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idempleado, nombre);
			return ((ISingleResult<SP_ConsultaPagoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ReporteRegalia")]
		public ISingleResult<SP_ReporteRegaliaResult> SP_ReporteRegalia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string banco, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), banco, fecha);
			return ((ISingleResult<SP_ReporteRegaliaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_ReportePagos")]
		public ISingleResult<Sp_ReportePagosResult> Sp_ReportePagos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string banco, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), banco, fecha);
			return ((ISingleResult<Sp_ReportePagosResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bancos")]
	public partial class Bancos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private System.DateTime _Fecha_Registro;
		
		private string _Estatus;
		
		private EntitySet<Empleados> _Empleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFecha_RegistroChanging(System.DateTime value);
    partial void OnFecha_RegistroChanged();
    partial void OnEstatusChanging(string value);
    partial void OnEstatusChanged();
    #endregion
		
		public Bancos()
		{
			this._Empleados = new EntitySet<Empleados>(new Action<Empleados>(this.attach_Empleados), new Action<Empleados>(this.detach_Empleados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Registro", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Registro
		{
			get
			{
				return this._Fecha_Registro;
			}
			set
			{
				if ((this._Fecha_Registro != value))
				{
					this.OnFecha_RegistroChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Registro = value;
					this.SendPropertyChanged("Fecha_Registro");
					this.OnFecha_RegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bancos_Empleados", Storage="_Empleados", ThisKey="Id", OtherKey="BancoID")]
		public EntitySet<Empleados> Empleados
		{
			get
			{
				return this._Empleados;
			}
			set
			{
				this._Empleados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empleados(Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Bancos = this;
		}
		
		private void detach_Empleados(Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Bancos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleados")]
	public partial class Empleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private int _Edad;
		
		private decimal _Sueldo_Fijo;
		
		private string _Cedula;
		
		private string _No_Cuenta;
		
		private string _Puesto;
		
		private System.DateTime _FechaIngreso;
		
		private int _EmpresaID;
		
		private int _SeguroID;
		
		private int _BancoID;
		
		private EntitySet<Regalias> _Regalias;
		
		private EntitySet<Pagos> _Pagos;
		
		private EntityRef<Bancos> _Bancos;
		
		private EntityRef<Empresas> _Empresas;
		
		private EntityRef<Seguros> _Seguros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnEdadChanging(int value);
    partial void OnEdadChanged();
    partial void OnSueldo_FijoChanging(decimal value);
    partial void OnSueldo_FijoChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnNo_CuentaChanging(string value);
    partial void OnNo_CuentaChanged();
    partial void OnPuestoChanging(string value);
    partial void OnPuestoChanged();
    partial void OnFechaIngresoChanging(System.DateTime value);
    partial void OnFechaIngresoChanged();
    partial void OnEmpresaIDChanging(int value);
    partial void OnEmpresaIDChanged();
    partial void OnSeguroIDChanging(int value);
    partial void OnSeguroIDChanged();
    partial void OnBancoIDChanging(int value);
    partial void OnBancoIDChanged();
    #endregion
		
		public Empleados()
		{
			this._Regalias = new EntitySet<Regalias>(new Action<Regalias>(this.attach_Regalias), new Action<Regalias>(this.detach_Regalias));
			this._Pagos = new EntitySet<Pagos>(new Action<Pagos>(this.attach_Pagos), new Action<Pagos>(this.detach_Pagos));
			this._Bancos = default(EntityRef<Bancos>);
			this._Empresas = default(EntityRef<Empresas>);
			this._Seguros = default(EntityRef<Seguros>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int NOT NULL")]
		public int Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this.OnEdadChanging(value);
					this.SendPropertyChanging();
					this._Edad = value;
					this.SendPropertyChanged("Edad");
					this.OnEdadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sueldo_Fijo", DbType="Decimal(18,2) NOT NULL")]
		public decimal Sueldo_Fijo
		{
			get
			{
				return this._Sueldo_Fijo;
			}
			set
			{
				if ((this._Sueldo_Fijo != value))
				{
					this.OnSueldo_FijoChanging(value);
					this.SendPropertyChanging();
					this._Sueldo_Fijo = value;
					this.SendPropertyChanged("Sueldo_Fijo");
					this.OnSueldo_FijoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Cuenta", DbType="VarChar(50)")]
		public string No_Cuenta
		{
			get
			{
				return this._No_Cuenta;
			}
			set
			{
				if ((this._No_Cuenta != value))
				{
					this.OnNo_CuentaChanging(value);
					this.SendPropertyChanging();
					this._No_Cuenta = value;
					this.SendPropertyChanged("No_Cuenta");
					this.OnNo_CuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puesto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Puesto
		{
			get
			{
				return this._Puesto;
			}
			set
			{
				if ((this._Puesto != value))
				{
					this.OnPuestoChanging(value);
					this.SendPropertyChanging();
					this._Puesto = value;
					this.SendPropertyChanged("Puesto");
					this.OnPuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIngreso", DbType="Date NOT NULL")]
		public System.DateTime FechaIngreso
		{
			get
			{
				return this._FechaIngreso;
			}
			set
			{
				if ((this._FechaIngreso != value))
				{
					this.OnFechaIngresoChanging(value);
					this.SendPropertyChanging();
					this._FechaIngreso = value;
					this.SendPropertyChanged("FechaIngreso");
					this.OnFechaIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpresaID", DbType="Int NOT NULL")]
		public int EmpresaID
		{
			get
			{
				return this._EmpresaID;
			}
			set
			{
				if ((this._EmpresaID != value))
				{
					if (this._Empresas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmpresaIDChanging(value);
					this.SendPropertyChanging();
					this._EmpresaID = value;
					this.SendPropertyChanged("EmpresaID");
					this.OnEmpresaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeguroID", DbType="Int NOT NULL")]
		public int SeguroID
		{
			get
			{
				return this._SeguroID;
			}
			set
			{
				if ((this._SeguroID != value))
				{
					if (this._Seguros.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSeguroIDChanging(value);
					this.SendPropertyChanging();
					this._SeguroID = value;
					this.SendPropertyChanged("SeguroID");
					this.OnSeguroIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BancoID", DbType="Int NOT NULL")]
		public int BancoID
		{
			get
			{
				return this._BancoID;
			}
			set
			{
				if ((this._BancoID != value))
				{
					if (this._Bancos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBancoIDChanging(value);
					this.SendPropertyChanging();
					this._BancoID = value;
					this.SendPropertyChanged("BancoID");
					this.OnBancoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleados_Regalias", Storage="_Regalias", ThisKey="Id", OtherKey="EmpleadoID")]
		public EntitySet<Regalias> Regalias
		{
			get
			{
				return this._Regalias;
			}
			set
			{
				this._Regalias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleados_Pagos", Storage="_Pagos", ThisKey="Id", OtherKey="EmpleadoID")]
		public EntitySet<Pagos> Pagos
		{
			get
			{
				return this._Pagos;
			}
			set
			{
				this._Pagos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bancos_Empleados", Storage="_Bancos", ThisKey="BancoID", OtherKey="Id", IsForeignKey=true)]
		public Bancos Bancos
		{
			get
			{
				return this._Bancos.Entity;
			}
			set
			{
				Bancos previousValue = this._Bancos.Entity;
				if (((previousValue != value) 
							|| (this._Bancos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bancos.Entity = null;
						previousValue.Empleados.Remove(this);
					}
					this._Bancos.Entity = value;
					if ((value != null))
					{
						value.Empleados.Add(this);
						this._BancoID = value.Id;
					}
					else
					{
						this._BancoID = default(int);
					}
					this.SendPropertyChanged("Bancos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresas_Empleados", Storage="_Empresas", ThisKey="EmpresaID", OtherKey="Id", IsForeignKey=true)]
		public Empresas Empresas
		{
			get
			{
				return this._Empresas.Entity;
			}
			set
			{
				Empresas previousValue = this._Empresas.Entity;
				if (((previousValue != value) 
							|| (this._Empresas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empresas.Entity = null;
						previousValue.Empleados.Remove(this);
					}
					this._Empresas.Entity = value;
					if ((value != null))
					{
						value.Empleados.Add(this);
						this._EmpresaID = value.Id;
					}
					else
					{
						this._EmpresaID = default(int);
					}
					this.SendPropertyChanged("Empresas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seguros_Empleados", Storage="_Seguros", ThisKey="SeguroID", OtherKey="Id", IsForeignKey=true)]
		public Seguros Seguros
		{
			get
			{
				return this._Seguros.Entity;
			}
			set
			{
				Seguros previousValue = this._Seguros.Entity;
				if (((previousValue != value) 
							|| (this._Seguros.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seguros.Entity = null;
						previousValue.Empleados.Remove(this);
					}
					this._Seguros.Entity = value;
					if ((value != null))
					{
						value.Empleados.Add(this);
						this._SeguroID = value.Id;
					}
					else
					{
						this._SeguroID = default(int);
					}
					this.SendPropertyChanged("Seguros");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Regalias(Regalias entity)
		{
			this.SendPropertyChanging();
			entity.Empleados = this;
		}
		
		private void detach_Regalias(Regalias entity)
		{
			this.SendPropertyChanging();
			entity.Empleados = null;
		}
		
		private void attach_Pagos(Pagos entity)
		{
			this.SendPropertyChanging();
			entity.Empleados = this;
		}
		
		private void detach_Pagos(Pagos entity)
		{
			this.SendPropertyChanging();
			entity.Empleados = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empresas")]
	public partial class Empresas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private System.DateTime _Fecha_Registro;
		
		private EntitySet<Empleados> _Empleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFecha_RegistroChanging(System.DateTime value);
    partial void OnFecha_RegistroChanged();
    #endregion
		
		public Empresas()
		{
			this._Empleados = new EntitySet<Empleados>(new Action<Empleados>(this.attach_Empleados), new Action<Empleados>(this.detach_Empleados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Registro", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Registro
		{
			get
			{
				return this._Fecha_Registro;
			}
			set
			{
				if ((this._Fecha_Registro != value))
				{
					this.OnFecha_RegistroChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Registro = value;
					this.SendPropertyChanged("Fecha_Registro");
					this.OnFecha_RegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresas_Empleados", Storage="_Empleados", ThisKey="Id", OtherKey="EmpresaID")]
		public EntitySet<Empleados> Empleados
		{
			get
			{
				return this._Empleados;
			}
			set
			{
				this._Empleados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empleados(Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Empresas = this;
		}
		
		private void detach_Empleados(Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Empresas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Regalias")]
	public partial class Regalias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private decimal _Monto;
		
		private System.DateTime _Fecha;
		
		private int _EmpleadoID;
		
		private EntityRef<Empleados> _Empleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMontoChanging(decimal value);
    partial void OnMontoChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnEmpleadoIDChanging(int value);
    partial void OnEmpleadoIDChanged();
    #endregion
		
		public Regalias()
		{
			this._Empleados = default(EntityRef<Empleados>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(18,2) NOT NULL")]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this.OnMontoChanging(value);
					this.SendPropertyChanging();
					this._Monto = value;
					this.SendPropertyChanged("Monto");
					this.OnMontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpleadoID", DbType="Int NOT NULL")]
		public int EmpleadoID
		{
			get
			{
				return this._EmpleadoID;
			}
			set
			{
				if ((this._EmpleadoID != value))
				{
					if (this._Empleados.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmpleadoIDChanging(value);
					this.SendPropertyChanging();
					this._EmpleadoID = value;
					this.SendPropertyChanged("EmpleadoID");
					this.OnEmpleadoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleados_Regalias", Storage="_Empleados", ThisKey="EmpleadoID", OtherKey="Id", IsForeignKey=true)]
		public Empleados Empleados
		{
			get
			{
				return this._Empleados.Entity;
			}
			set
			{
				Empleados previousValue = this._Empleados.Entity;
				if (((previousValue != value) 
							|| (this._Empleados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleados.Entity = null;
						previousValue.Regalias.Remove(this);
					}
					this._Empleados.Entity = value;
					if ((value != null))
					{
						value.Regalias.Add(this);
						this._EmpleadoID = value.Id;
					}
					else
					{
						this._EmpleadoID = default(int);
					}
					this.SendPropertyChanged("Empleados");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seguros")]
	public partial class Seguros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private System.DateTime _Fecha_Registro;
		
		private EntitySet<Empleados> _Empleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFecha_RegistroChanging(System.DateTime value);
    partial void OnFecha_RegistroChanged();
    #endregion
		
		public Seguros()
		{
			this._Empleados = new EntitySet<Empleados>(new Action<Empleados>(this.attach_Empleados), new Action<Empleados>(this.detach_Empleados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Registro", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Registro
		{
			get
			{
				return this._Fecha_Registro;
			}
			set
			{
				if ((this._Fecha_Registro != value))
				{
					this.OnFecha_RegistroChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Registro = value;
					this.SendPropertyChanged("Fecha_Registro");
					this.OnFecha_RegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seguros_Empleados", Storage="_Empleados", ThisKey="Id", OtherKey="SeguroID")]
		public EntitySet<Empleados> Empleados
		{
			get
			{
				return this._Empleados;
			}
			set
			{
				this._Empleados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empleados(Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Seguros = this;
		}
		
		private void detach_Empleados(Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Seguros = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pagos")]
	public partial class Pagos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _Fecha;
		
		private System.Nullable<decimal> _Impuesto;
		
		private System.Nullable<decimal> _Total_Cobrado;
		
		private System.Nullable<decimal> _Reembolso_Gastos;
		
		private System.Nullable<decimal> _Horas_Extras;
		
		private System.Nullable<decimal> _Bono_Especial;
		
		private System.Nullable<decimal> _Seguro_Salud;
		
		private System.Nullable<decimal> _Adicional;
		
		private int _EmpleadoID;
		
		private System.Nullable<decimal> _SueldoBruto;
		
		private EntityRef<Empleados> _Empleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnImpuestoChanging(System.Nullable<decimal> value);
    partial void OnImpuestoChanged();
    partial void OnTotal_CobradoChanging(System.Nullable<decimal> value);
    partial void OnTotal_CobradoChanged();
    partial void OnReembolso_GastosChanging(System.Nullable<decimal> value);
    partial void OnReembolso_GastosChanged();
    partial void OnHoras_ExtrasChanging(System.Nullable<decimal> value);
    partial void OnHoras_ExtrasChanged();
    partial void OnBono_EspecialChanging(System.Nullable<decimal> value);
    partial void OnBono_EspecialChanged();
    partial void OnSeguro_SaludChanging(System.Nullable<decimal> value);
    partial void OnSeguro_SaludChanged();
    partial void OnAdicionalChanging(System.Nullable<decimal> value);
    partial void OnAdicionalChanged();
    partial void OnEmpleadoIDChanging(int value);
    partial void OnEmpleadoIDChanged();
    partial void OnSueldoBrutoChanging(System.Nullable<decimal> value);
    partial void OnSueldoBrutoChanged();
    #endregion
		
		public Pagos()
		{
			this._Empleados = default(EntityRef<Empleados>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this.OnImpuestoChanging(value);
					this.SendPropertyChanging();
					this._Impuesto = value;
					this.SendPropertyChanged("Impuesto");
					this.OnImpuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cobrado", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total_Cobrado
		{
			get
			{
				return this._Total_Cobrado;
			}
			set
			{
				if ((this._Total_Cobrado != value))
				{
					this.OnTotal_CobradoChanging(value);
					this.SendPropertyChanging();
					this._Total_Cobrado = value;
					this.SendPropertyChanged("Total_Cobrado");
					this.OnTotal_CobradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reembolso_Gastos", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Reembolso_Gastos
		{
			get
			{
				return this._Reembolso_Gastos;
			}
			set
			{
				if ((this._Reembolso_Gastos != value))
				{
					this.OnReembolso_GastosChanging(value);
					this.SendPropertyChanging();
					this._Reembolso_Gastos = value;
					this.SendPropertyChanged("Reembolso_Gastos");
					this.OnReembolso_GastosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horas_Extras", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Horas_Extras
		{
			get
			{
				return this._Horas_Extras;
			}
			set
			{
				if ((this._Horas_Extras != value))
				{
					this.OnHoras_ExtrasChanging(value);
					this.SendPropertyChanging();
					this._Horas_Extras = value;
					this.SendPropertyChanged("Horas_Extras");
					this.OnHoras_ExtrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bono_Especial", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Bono_Especial
		{
			get
			{
				return this._Bono_Especial;
			}
			set
			{
				if ((this._Bono_Especial != value))
				{
					this.OnBono_EspecialChanging(value);
					this.SendPropertyChanging();
					this._Bono_Especial = value;
					this.SendPropertyChanged("Bono_Especial");
					this.OnBono_EspecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seguro_Salud", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Seguro_Salud
		{
			get
			{
				return this._Seguro_Salud;
			}
			set
			{
				if ((this._Seguro_Salud != value))
				{
					this.OnSeguro_SaludChanging(value);
					this.SendPropertyChanging();
					this._Seguro_Salud = value;
					this.SendPropertyChanged("Seguro_Salud");
					this.OnSeguro_SaludChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adicional", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Adicional
		{
			get
			{
				return this._Adicional;
			}
			set
			{
				if ((this._Adicional != value))
				{
					this.OnAdicionalChanging(value);
					this.SendPropertyChanging();
					this._Adicional = value;
					this.SendPropertyChanged("Adicional");
					this.OnAdicionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpleadoID", DbType="Int NOT NULL")]
		public int EmpleadoID
		{
			get
			{
				return this._EmpleadoID;
			}
			set
			{
				if ((this._EmpleadoID != value))
				{
					if (this._Empleados.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmpleadoIDChanging(value);
					this.SendPropertyChanging();
					this._EmpleadoID = value;
					this.SendPropertyChanged("EmpleadoID");
					this.OnEmpleadoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SueldoBruto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SueldoBruto
		{
			get
			{
				return this._SueldoBruto;
			}
			set
			{
				if ((this._SueldoBruto != value))
				{
					this.OnSueldoBrutoChanging(value);
					this.SendPropertyChanging();
					this._SueldoBruto = value;
					this.SendPropertyChanged("SueldoBruto");
					this.OnSueldoBrutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleados_Pagos", Storage="_Empleados", ThisKey="EmpleadoID", OtherKey="Id", IsForeignKey=true)]
		public Empleados Empleados
		{
			get
			{
				return this._Empleados.Entity;
			}
			set
			{
				Empleados previousValue = this._Empleados.Entity;
				if (((previousValue != value) 
							|| (this._Empleados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleados.Entity = null;
						previousValue.Pagos.Remove(this);
					}
					this._Empleados.Entity = value;
					if ((value != null))
					{
						value.Pagos.Add(this);
						this._EmpleadoID = value.Id;
					}
					else
					{
						this._EmpleadoID = default(int);
					}
					this.SendPropertyChanged("Empleados");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Sp_ConsultaBancosResult
	{
		
		private int _Codigo_del_Banco;
		
		private string _Nombre;
		
		private System.DateTime _Fecha_Registro;
		
		private string _Estatus;
		
		public Sp_ConsultaBancosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo del Banco]", Storage="_Codigo_del_Banco", DbType="Int NOT NULL")]
		public int Codigo_del_Banco
		{
			get
			{
				return this._Codigo_del_Banco;
			}
			set
			{
				if ((this._Codigo_del_Banco != value))
				{
					this._Codigo_del_Banco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Registro]", Storage="_Fecha_Registro", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Registro
		{
			get
			{
				return this._Fecha_Registro;
			}
			set
			{
				if ((this._Fecha_Registro != value))
				{
					this._Fecha_Registro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
	}
	
	public partial class Sp_BuscarBancosResult
	{
		
		private int _Codigo_del_Banco;
		
		private string _Nombre;
		
		private System.DateTime _Fecha_Registro;
		
		private string _Estatus;
		
		public Sp_BuscarBancosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo del Banco]", Storage="_Codigo_del_Banco", DbType="Int NOT NULL")]
		public int Codigo_del_Banco
		{
			get
			{
				return this._Codigo_del_Banco;
			}
			set
			{
				if ((this._Codigo_del_Banco != value))
				{
					this._Codigo_del_Banco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Registro]", Storage="_Fecha_Registro", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Registro
		{
			get
			{
				return this._Fecha_Registro;
			}
			set
			{
				if ((this._Fecha_Registro != value))
				{
					this._Fecha_Registro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
	}
	
	public partial class Sp_BuscarEmpresasResult
	{
		
		private int _Codigo_del_Empresa;
		
		private string _Nombre;
		
		private System.DateTime _Fecha_Registro;
		
		public Sp_BuscarEmpresasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo del Empresa]", Storage="_Codigo_del_Empresa", DbType="Int NOT NULL")]
		public int Codigo_del_Empresa
		{
			get
			{
				return this._Codigo_del_Empresa;
			}
			set
			{
				if ((this._Codigo_del_Empresa != value))
				{
					this._Codigo_del_Empresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Registro]", Storage="_Fecha_Registro", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Registro
		{
			get
			{
				return this._Fecha_Registro;
			}
			set
			{
				if ((this._Fecha_Registro != value))
				{
					this._Fecha_Registro = value;
				}
			}
		}
	}
	
	public partial class Sp_ConsultarEmpresasResult
	{
		
		private int _Codigo_de_Empresa;
		
		private string _Nombre;
		
		private System.DateTime _Fecha_Registro;
		
		public Sp_ConsultarEmpresasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo de Empresa]", Storage="_Codigo_de_Empresa", DbType="Int NOT NULL")]
		public int Codigo_de_Empresa
		{
			get
			{
				return this._Codigo_de_Empresa;
			}
			set
			{
				if ((this._Codigo_de_Empresa != value))
				{
					this._Codigo_de_Empresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Registro]", Storage="_Fecha_Registro", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Registro
		{
			get
			{
				return this._Fecha_Registro;
			}
			set
			{
				if ((this._Fecha_Registro != value))
				{
					this._Fecha_Registro = value;
				}
			}
		}
	}
	
	public partial class Sp_BuscarSegurosResult
	{
		
		private int _Codigo_del_Seguro;
		
		private string _Nombre;
		
		private System.DateTime _Fecha_Registro;
		
		public Sp_BuscarSegurosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo del Seguro]", Storage="_Codigo_del_Seguro", DbType="Int NOT NULL")]
		public int Codigo_del_Seguro
		{
			get
			{
				return this._Codigo_del_Seguro;
			}
			set
			{
				if ((this._Codigo_del_Seguro != value))
				{
					this._Codigo_del_Seguro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Registro]", Storage="_Fecha_Registro", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Registro
		{
			get
			{
				return this._Fecha_Registro;
			}
			set
			{
				if ((this._Fecha_Registro != value))
				{
					this._Fecha_Registro = value;
				}
			}
		}
	}
	
	public partial class Sp_ConsultarSegurosResult
	{
		
		private int _Codigo_del_Seguro;
		
		private string _Nombre;
		
		private System.DateTime _Fecha_Registro;
		
		public Sp_ConsultarSegurosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo del Seguro]", Storage="_Codigo_del_Seguro", DbType="Int NOT NULL")]
		public int Codigo_del_Seguro
		{
			get
			{
				return this._Codigo_del_Seguro;
			}
			set
			{
				if ((this._Codigo_del_Seguro != value))
				{
					this._Codigo_del_Seguro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Registro]", Storage="_Fecha_Registro", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Registro
		{
			get
			{
				return this._Fecha_Registro;
			}
			set
			{
				if ((this._Fecha_Registro != value))
				{
					this._Fecha_Registro = value;
				}
			}
		}
	}
	
	public partial class Sp_BuscarEmpleadosResult
	{
		
		private int _Codigo_del_Empleado;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private int _Edad;
		
		private decimal _Sueldo_Fijo;
		
		private string _Cedula;
		
		private string _No_Cuenta;
		
		private string _Puesto;
		
		private System.DateTime _Fecha_de_Ingreso;
		
		private string _Empresa;
		
		private string _Seguro;
		
		private string _Banco;
		
		public Sp_BuscarEmpleadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo del Empleado]", Storage="_Codigo_del_Empleado", DbType="Int NOT NULL")]
		public int Codigo_del_Empleado
		{
			get
			{
				return this._Codigo_del_Empleado;
			}
			set
			{
				if ((this._Codigo_del_Empleado != value))
				{
					this._Codigo_del_Empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int NOT NULL")]
		public int Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sueldo_Fijo", DbType="Decimal(18,2) NOT NULL")]
		public decimal Sueldo_Fijo
		{
			get
			{
				return this._Sueldo_Fijo;
			}
			set
			{
				if ((this._Sueldo_Fijo != value))
				{
					this._Sueldo_Fijo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Cuenta", DbType="VarChar(50)")]
		public string No_Cuenta
		{
			get
			{
				return this._No_Cuenta;
			}
			set
			{
				if ((this._No_Cuenta != value))
				{
					this._No_Cuenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puesto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Puesto
		{
			get
			{
				return this._Puesto;
			}
			set
			{
				if ((this._Puesto != value))
				{
					this._Puesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Ingreso]", Storage="_Fecha_de_Ingreso", DbType="Date NOT NULL")]
		public System.DateTime Fecha_de_Ingreso
		{
			get
			{
				return this._Fecha_de_Ingreso;
			}
			set
			{
				if ((this._Fecha_de_Ingreso != value))
				{
					this._Fecha_de_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empresa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				if ((this._Empresa != value))
				{
					this._Empresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seguro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Seguro
		{
			get
			{
				return this._Seguro;
			}
			set
			{
				if ((this._Seguro != value))
				{
					this._Seguro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banco", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Banco
		{
			get
			{
				return this._Banco;
			}
			set
			{
				if ((this._Banco != value))
				{
					this._Banco = value;
				}
			}
		}
	}
	
	public partial class Sp_ConsultaEmpleadosResult
	{
		
		private int _Codigo_del_Empleado;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private int _Edad;
		
		private decimal _Sueldo_Fijo;
		
		private string _Cedula;
		
		private string _No_Cuenta;
		
		private string _Puesto;
		
		private System.DateTime _Fecha_de_Ingreso;
		
		private string _Empresa;
		
		private string _Seguro;
		
		private string _Banco;
		
		public Sp_ConsultaEmpleadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo del Empleado]", Storage="_Codigo_del_Empleado", DbType="Int NOT NULL")]
		public int Codigo_del_Empleado
		{
			get
			{
				return this._Codigo_del_Empleado;
			}
			set
			{
				if ((this._Codigo_del_Empleado != value))
				{
					this._Codigo_del_Empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int NOT NULL")]
		public int Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sueldo_Fijo", DbType="Decimal(18,2) NOT NULL")]
		public decimal Sueldo_Fijo
		{
			get
			{
				return this._Sueldo_Fijo;
			}
			set
			{
				if ((this._Sueldo_Fijo != value))
				{
					this._Sueldo_Fijo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Cuenta", DbType="VarChar(50)")]
		public string No_Cuenta
		{
			get
			{
				return this._No_Cuenta;
			}
			set
			{
				if ((this._No_Cuenta != value))
				{
					this._No_Cuenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puesto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Puesto
		{
			get
			{
				return this._Puesto;
			}
			set
			{
				if ((this._Puesto != value))
				{
					this._Puesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Ingreso]", Storage="_Fecha_de_Ingreso", DbType="Date NOT NULL")]
		public System.DateTime Fecha_de_Ingreso
		{
			get
			{
				return this._Fecha_de_Ingreso;
			}
			set
			{
				if ((this._Fecha_de_Ingreso != value))
				{
					this._Fecha_de_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empresa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				if ((this._Empresa != value))
				{
					this._Empresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seguro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Seguro
		{
			get
			{
				return this._Seguro;
			}
			set
			{
				if ((this._Seguro != value))
				{
					this._Seguro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banco", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Banco
		{
			get
			{
				return this._Banco;
			}
			set
			{
				if ((this._Banco != value))
				{
					this._Banco = value;
				}
			}
		}
	}
	
	public partial class ConsultaPagoRegistradoResult
	{
		
		private System.DateTime _Fecha;
		
		private System.Nullable<decimal> _Impuesto;
		
		private System.Nullable<decimal> _Total_Cobrado;
		
		private System.Nullable<decimal> _Reembolso_Gastos;
		
		private System.Nullable<decimal> _Horas_Extras;
		
		private System.Nullable<decimal> _Bono_Especial;
		
		private System.Nullable<decimal> _Seguro_Salud;
		
		private System.Nullable<decimal> _Adicional;
		
		public ConsultaPagoRegistradoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this._Impuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cobrado", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total_Cobrado
		{
			get
			{
				return this._Total_Cobrado;
			}
			set
			{
				if ((this._Total_Cobrado != value))
				{
					this._Total_Cobrado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reembolso_Gastos", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Reembolso_Gastos
		{
			get
			{
				return this._Reembolso_Gastos;
			}
			set
			{
				if ((this._Reembolso_Gastos != value))
				{
					this._Reembolso_Gastos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horas_Extras", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Horas_Extras
		{
			get
			{
				return this._Horas_Extras;
			}
			set
			{
				if ((this._Horas_Extras != value))
				{
					this._Horas_Extras = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bono_Especial", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Bono_Especial
		{
			get
			{
				return this._Bono_Especial;
			}
			set
			{
				if ((this._Bono_Especial != value))
				{
					this._Bono_Especial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seguro_Salud", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Seguro_Salud
		{
			get
			{
				return this._Seguro_Salud;
			}
			set
			{
				if ((this._Seguro_Salud != value))
				{
					this._Seguro_Salud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adicional", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Adicional
		{
			get
			{
				return this._Adicional;
			}
			set
			{
				if ((this._Adicional != value))
				{
					this._Adicional = value;
				}
			}
		}
	}
	
	public partial class Sp_ConsultaRegaliaResult
	{
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private decimal _Monto;
		
		private System.DateTime _Fecha;
		
		public Sp_ConsultaRegaliaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(18,2) NOT NULL")]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class SP_ConsultaPagoResult
	{
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Banco;
		
		private System.DateTime _Fecha;
		
		private System.Nullable<decimal> _Impuesto;
		
		private System.Nullable<decimal> _Total_Cobrado;
		
		private System.Nullable<decimal> _Reembolso_Gastos;
		
		private System.Nullable<decimal> _Horas_Extras;
		
		private System.Nullable<decimal> _Bono_Especial;
		
		private System.Nullable<decimal> _Seguro_Salud;
		
		private System.Nullable<decimal> _Adicional;
		
		private System.Nullable<decimal> _SueldoBruto;
		
		public SP_ConsultaPagoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banco", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Banco
		{
			get
			{
				return this._Banco;
			}
			set
			{
				if ((this._Banco != value))
				{
					this._Banco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this._Impuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cobrado", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total_Cobrado
		{
			get
			{
				return this._Total_Cobrado;
			}
			set
			{
				if ((this._Total_Cobrado != value))
				{
					this._Total_Cobrado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reembolso_Gastos", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Reembolso_Gastos
		{
			get
			{
				return this._Reembolso_Gastos;
			}
			set
			{
				if ((this._Reembolso_Gastos != value))
				{
					this._Reembolso_Gastos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horas_Extras", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Horas_Extras
		{
			get
			{
				return this._Horas_Extras;
			}
			set
			{
				if ((this._Horas_Extras != value))
				{
					this._Horas_Extras = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bono_Especial", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Bono_Especial
		{
			get
			{
				return this._Bono_Especial;
			}
			set
			{
				if ((this._Bono_Especial != value))
				{
					this._Bono_Especial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seguro_Salud", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Seguro_Salud
		{
			get
			{
				return this._Seguro_Salud;
			}
			set
			{
				if ((this._Seguro_Salud != value))
				{
					this._Seguro_Salud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adicional", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Adicional
		{
			get
			{
				return this._Adicional;
			}
			set
			{
				if ((this._Adicional != value))
				{
					this._Adicional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SueldoBruto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SueldoBruto
		{
			get
			{
				return this._SueldoBruto;
			}
			set
			{
				if ((this._SueldoBruto != value))
				{
					this._SueldoBruto = value;
				}
			}
		}
	}
	
	public partial class SP_ReporteRegaliaResult
	{
		
		private string _Banco;
		
		private string _Estatus;
		
		private decimal _Monto_Cobrado;
		
		public SP_ReporteRegaliaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banco", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Banco
		{
			get
			{
				return this._Banco;
			}
			set
			{
				if ((this._Banco != value))
				{
					this._Banco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Monto Cobrado]", Storage="_Monto_Cobrado", DbType="Decimal(18,2) NOT NULL")]
		public decimal Monto_Cobrado
		{
			get
			{
				return this._Monto_Cobrado;
			}
			set
			{
				if ((this._Monto_Cobrado != value))
				{
					this._Monto_Cobrado = value;
				}
			}
		}
	}
	
	public partial class Sp_ReportePagosResult
	{
		
		private string _Banco;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _Descuentos;
		
		private System.Nullable<decimal> _Sub_Total;
		
		public Sp_ReportePagosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banco", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Banco
		{
			get
			{
				return this._Banco;
			}
			set
			{
				if ((this._Banco != value))
				{
					this._Banco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuentos", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> Descuentos
		{
			get
			{
				return this._Descuentos;
			}
			set
			{
				if ((this._Descuentos != value))
				{
					this._Descuentos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sub-Total]", Storage="_Sub_Total", DbType="Decimal(24,2)")]
		public System.Nullable<decimal> Sub_Total
		{
			get
			{
				return this._Sub_Total;
			}
			set
			{
				if ((this._Sub_Total != value))
				{
					this._Sub_Total = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
